// <auto-generated />
namespace MariaDB.Data.Common
{
    using System.Globalization;
    using System.Reflection;
    using System.Resources;
    

    public static class ResourceStrings
    {
        private static readonly ResourceManager _resourceManager
            = new ResourceManager("MariaDB.Data.Common.MySqlStrings", typeof(ResourceStrings).GetTypeInfo().Assembly);

        private static CultureInfo resourceCulture = CultureInfo.CurrentCulture;

        /// <summary>
        ///   Looks up a localized string similar to Improper MySqlCommandBuilder state: adapter is null.
        /// </summary>
        public static string AdapterIsNull
        {
            get
            {
                return _resourceManager.GetString("AdapterIsNull", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Improper MySqlCommandBuilder state: adapter&apos;s SelectCommand is null.
        /// </summary>
        public static string AdapterSelectIsNull
        {
            get
            {
                return _resourceManager.GetString("AdapterSelectIsNull", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid attempt to access a field before calling Read().
        /// </summary>
        public static string AttemptToAccessBeforeRead
        {
            get
            {
                return _resourceManager.GetString("AttemptToAccessBeforeRead", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Version string not in acceptable format.
        /// </summary>
        public static string BadVersionFormat
        {
            get
            {
                return _resourceManager.GetString("BadVersionFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to  The buffer cannot be null.
        /// </summary>
        public static string BufferCannotBeNull
        {
            get
            {
                return _resourceManager.GetString("BufferCannotBeNull", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to  Buffer is not large enough.
        /// </summary>
        public static string BufferNotLargeEnough
        {
            get
            {
                return _resourceManager.GetString("BufferNotLargeEnough", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Canceling an executing query requires MySQL 5.0 or higher..
        /// </summary>
        public static string CancelNeeds50
        {
            get
            {
                return _resourceManager.GetString("CancelNeeds50", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Canceling an active query is only supported on MySQL 5.0.0 and above. .
        /// </summary>
        public static string CancelNotSupported
        {
            get
            {
                return _resourceManager.GetString("CancelNotSupported", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Parameters can only be derived for commands using the StoredProcedure command type..
        /// </summary>
        public static string CanNotDeriveParametersForTextCommands
        {
            get
            {
                return _resourceManager.GetString("CanNotDeriveParametersForTextCommands", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MySqlCommandBuilder does not support multi-table statements.
        /// </summary>
        public static string CBMultiTableNotSupported
        {
            get
            {
                return _resourceManager.GetString("CBMultiTableNotSupported", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MySqlCommandBuilder cannot operate on tables with no unique or key columns.
        /// </summary>
        public static string CBNoKeyColumn
        {
            get
            {
                return _resourceManager.GetString("CBNoKeyColumn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Chaos isolation level is not supported.
        /// </summary>
        public static string ChaosNotSupported
        {
            get
            {
                return _resourceManager.GetString("ChaosNotSupported", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The CommandText property has not been properly initialized..
        /// </summary>
        public static string CommandTextNotInitialized
        {
            get
            {
                return _resourceManager.GetString("CommandTextNotInitialized", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The connection is already open..
        /// </summary>
        public static string ConnectionAlreadyOpen
        {
            get
            {
                return _resourceManager.GetString("ConnectionAlreadyOpen", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connection unexpectedly terminated..
        /// </summary>
        public static string ConnectionBroken
        {
            get
            {
                return _resourceManager.GetString("ConnectionBroken", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connection must be valid and open.
        /// </summary>
        public static string ConnectionMustBeOpen
        {
            get
            {
                return _resourceManager.GetString("ConnectionMustBeOpen", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The connection is not open..
        /// </summary>
        public static string ConnectionNotOpen
        {
            get
            {
                return _resourceManager.GetString("ConnectionNotOpen", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The connection property has not been set or is null..
        /// </summary>
        public static string ConnectionNotSet
        {
            get
            {
                return _resourceManager.GetString("ConnectionNotSet", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not find specified column in results: {0}.
        /// </summary>
        public static string CouldNotFindColumnName
        {
            get
            {
                return _resourceManager.GetString("CouldNotFindColumnName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to  Count cannot be negative.
        /// </summary>
        public static string CountCannotBeNegative
        {
            get
            {
                return _resourceManager.GetString("CountCannotBeNegative", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SetLength is not a valid operation on CompressedStream.
        /// </summary>
        public static string CSNoSetLength
        {
            get
            {
                return _resourceManager.GetString("CSNoSetLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The given value was not in a supported format..
        /// </summary>
        public static string DataNotInSupportedFormat
        {
            get
            {
                return _resourceManager.GetString("DataNotInSupportedFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to There is already an open DataReader associated with this Connection which must be closed first..
        /// </summary>
        public static string DataReaderOpen
        {
            get
            {
                return _resourceManager.GetString("DataReaderOpen", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The default connection encoding was not found. Please report this as a bug along with your connection string and system details..
        /// </summary>
        public static string DefaultEncodingNotFound
        {
            get
            {
                return _resourceManager.GetString("DefaultEncodingNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MySQL Connector/Net does not currently support distributed transactions..
        /// </summary>
        public static string DistributedTxnNotSupported
        {
            get
            {
                return _resourceManager.GetString("DistributedTxnNotSupported", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error creating socket connection.
        /// </summary>
        public static string ErrorCreatingSocket
        {
            get
            {
                return _resourceManager.GetString("ErrorCreatingSocket", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Fatal error encountered during command execution..
        /// </summary>
        public static string FatalErrorDuringExecute
        {
            get
            {
                return _resourceManager.GetString("FatalErrorDuringExecute", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Fatal error encountered during data read..
        /// </summary>
        public static string FatalErrorDuringRead
        {
            get
            {
                return _resourceManager.GetString("FatalErrorDuringRead", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Fatal error encountered attempting to read the resultset..
        /// </summary>
        public static string FatalErrorReadingResult
        {
            get
            {
                return _resourceManager.GetString("FatalErrorReadingResult", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File based certificates are only supported when connecting to MySQL Server 5.1 or greater..
        /// </summary>
        public static string FileBasedCertificateNotSupported
        {
            get
            {
                return _resourceManager.GetString("FileBasedCertificateNotSupported", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to From index and length use more bytes than from contains.
        /// </summary>
        public static string FromAndLengthTooBig
        {
            get
            {
                return _resourceManager.GetString("FromAndLengthTooBig", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to From index must be a valid index inside the from buffer.
        /// </summary>
        public static string FromIndexMustBeValid
        {
            get
            {
                return _resourceManager.GetString("FromIndexMustBeValid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Call to GetHostEntry failed after {0} while querying for hostname &apos;{1}&apos;: SocketErrorCode={2}, ErrorCode={3}, NativeErrorCode={4}..
        /// </summary>
        public static string GetHostEntryFailed
        {
            get
            {
                return _resourceManager.GetString("GetHostEntryFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Retrieving procedure metadata for {0} from server..
        /// </summary>
        public static string HardProcQuery
        {
            get
            {
                return _resourceManager.GetString("HardProcQuery", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Value has an unsupported format..
        /// </summary>
        public static string ImproperValueFormat
        {
            get
            {
                return _resourceManager.GetString("ImproperValueFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An incorrect response was received from the server..
        /// </summary>
        public static string IncorrectTransmission
        {
            get
            {
                return _resourceManager.GetString("IncorrectTransmission", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Index and length use more bytes than to has room for.
        /// </summary>
        public static string IndexAndLengthTooBig
        {
            get
            {
                return _resourceManager.GetString("IndexAndLengthTooBig", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Index must be a valid position in the buffer.
        /// </summary>
        public static string IndexMustBeValid
        {
            get
            {
                return _resourceManager.GetString("IndexMustBeValid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You have specified an invalid column ordinal..
        /// </summary>
        public static string InvalidColumnOrdinal
        {
            get
            {
                return _resourceManager.GetString("InvalidColumnOrdinal", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The requested value &apos;{0}&apos; is invalid for the given keyword &apos;{1}&apos;..
        /// </summary>
        public static string InvalidConnectionStringValue
        {
            get
            {
                return _resourceManager.GetString("InvalidConnectionStringValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Procedure or function &apos;{0}&apos; cannot be found in database &apos;{1}&apos;..
        /// </summary>
        public static string InvalidProcName
        {
            get
            {
                return _resourceManager.GetString("InvalidProcName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an illegal value for a boolean option..
        /// </summary>
        public static string InvalidValueForBoolean
        {
            get
            {
                return _resourceManager.GetString("InvalidValueForBoolean", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Keyword does not allow null values..
        /// </summary>
        public static string KeywordNoNull
        {
            get
            {
                return _resourceManager.GetString("KeywordNoNull", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Keyword not supported..
        /// </summary>
        public static string KeywordNotSupported
        {
            get
            {
                return _resourceManager.GetString("KeywordNotSupported", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ACCESSIBLE
        ///ADD
        ///ALL
        ///ALTER
        ///ANALYZE
        ///AND
        ///AS
        ///ASC
        ///ASENSITIVE
        ///BEFORE
        ///BETWEEN
        ///BIGINT
        ///BINARY
        ///BLOB
        ///BOTH
        ///BY
        ///CALL
        ///CASCADE
        ///CASE
        ///CHANGE
        ///CHAR
        ///CHARACTER
        ///CHECK
        ///COLLATE
        ///COLUMN
        ///CONDITION
        ///CONNECTION
        ///CONSTRAINT
        ///CONTINUE
        ///CONVERT
        ///CREATE
        ///CROSS
        ///CURRENT_DATE
        ///CURRENT_TIME
        ///CURRENT_TIMESTAMP
        ///CURRENT_USER
        ///CURSOR
        ///DATABASE
        ///DATABASES
        ///DAY_HOUR
        ///DAY_MICROSECOND
        ///DAY_MINUTE
        ///DAY_SECOND
        ///DEC
        ///DECIMAL
        ///DECLARE
        ///DEFAULT
        ///DELAYED
        ///DELETE
        ///DESC
        ///DESCRIBE
        ///DETERMINISTIC
        ///DISTINCT
        ///DISTINCTROW
        ///DIV
        ///DOUBLE
        ///DRO [rest of string was truncated]&quot;;.
        /// </summary>
        public static string keywords
        {
            get
            {
                return _resourceManager.GetString("keywords", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to INTERNAL ERROR:  More than one output parameter row detected..
        /// </summary>
        public static string MoreThanOneOPRow
        {
            get
            {
                return _resourceManager.GetString("MoreThanOneOPRow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Multiple simultaneous connections or connections with different connection strings inside the same transaction are not currently supported..
        /// </summary>
        public static string MultipleConnectionsInTransactionNotSupported
        {
            get
            {
                return _resourceManager.GetString("MultipleConnectionsInTransactionNotSupported", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NamedPipeStream does not support seeking.
        /// </summary>
        public static string NamedPipeNoSeek
        {
            get
            {
                return _resourceManager.GetString("NamedPipeNoSeek", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NamedPipeStream doesn&apos;t support SetLength.
        /// </summary>
        public static string NamedPipeNoSetLength
        {
            get
            {
                return _resourceManager.GetString("NamedPipeNoSetLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid attempt to call NextResult when the reader is closed..
        /// </summary>
        public static string NextResultIsClosed
        {
            get
            {
                return _resourceManager.GetString("NextResultIsClosed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to When calling stored procedures and &apos;Use Procedure Bodies&apos; is false, all parameters must have their type explicitly set..
        /// </summary>
        public static string NoBodiesAndTypeNotSet
        {
            get
            {
                return _resourceManager.GetString("NoBodiesAndTypeNotSet", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nested transactions are not supported..
        /// </summary>
        public static string NoNestedTransactions
        {
            get
            {
                return _resourceManager.GetString("NoNestedTransactions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The host {0} does not support SSL connections..
        /// </summary>
        public static string NoServerSSLSupport
        {
            get
            {
                return _resourceManager.GetString("NoServerSSLSupport", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot retrieve Windows identity for current user. Connections that use  IntegratedSecurity cannot be  pooled. Use either &apos;ConnectionReset=true&apos; or  &apos;Pooling=false&apos; in the connection string to fix..
        /// </summary>
        public static string NoWindowsIdentity
        {
            get
            {
                return _resourceManager.GetString("NoWindowsIdentity", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The object is not open or has been disposed..
        /// </summary>
        public static string ObjectDisposed
        {
            get
            {
                return _resourceManager.GetString("ObjectDisposed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to  Offset cannot be negative.
        /// </summary>
        public static string OffsetCannotBeNegative
        {
            get
            {
                return _resourceManager.GetString("OffsetCannotBeNegative", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Offset must be a valid position in buffer.
        /// </summary>
        public static string OffsetMustBeValid
        {
            get
            {
                return _resourceManager.GetString("OffsetMustBeValid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; has already been defined..
        /// </summary>
        public static string ParameterAlreadyDefined
        {
            get
            {
                return _resourceManager.GetString("ParameterAlreadyDefined", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Parameter cannot have a negative value.
        /// </summary>
        public static string ParameterCannotBeNegative
        {
            get
            {
                return _resourceManager.GetString("ParameterCannotBeNegative", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Parameter cannot be null.
        /// </summary>
        public static string ParameterCannotBeNull
        {
            get
            {
                return _resourceManager.GetString("ParameterCannotBeNull", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Parameter is invalid..
        /// </summary>
        public static string ParameterIsInvalid
        {
            get
            {
                return _resourceManager.GetString("ParameterIsInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; must be defined..
        /// </summary>
        public static string ParameterMustBeDefined
        {
            get
            {
                return _resourceManager.GetString("ParameterMustBeDefined", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; was not found during prepare..
        /// </summary>
        public static string ParameterNotFoundDuringPrepare
        {
            get
            {
                return _resourceManager.GetString("ParameterNotFoundDuringPrepare", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password must be valid and contain length characters.
        /// </summary>
        public static string PasswordMustHaveLegalChars
        {
            get
            {
                return _resourceManager.GetString("PasswordMustHaveLegalChars", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This category includes a series of counters for MySQL..
        /// </summary>
        public static string PerfMonCategoryHelp
        {
            get
            {
                return _resourceManager.GetString("PerfMonCategoryHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .NET Data Provider for MySQL.
        /// </summary>
        public static string PerfMonCategoryName
        {
            get
            {
                return _resourceManager.GetString("PerfMonCategoryName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The number of times a procedures metadata had to be queried from the server..
        /// </summary>
        public static string PerfMonHardProcHelp
        {
            get
            {
                return _resourceManager.GetString("PerfMonHardProcHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hard Procedure Queries.
        /// </summary>
        public static string PerfMonHardProcName
        {
            get
            {
                return _resourceManager.GetString("PerfMonHardProcName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The number of times a procedures metadata was retrieved from the client-side cache..
        /// </summary>
        public static string PerfMonSoftProcHelp
        {
            get
            {
                return _resourceManager.GetString("PerfMonSoftProcHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Soft Procedure Queries.
        /// </summary>
        public static string PerfMonSoftProcName
        {
            get
            {
                return _resourceManager.GetString("PerfMonSoftProcName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to same name are not supported..
        /// </summary>
        public static string ProcAndFuncSameName
        {
            get
            {
                return _resourceManager.GetString("ProcAndFuncSameName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Packets larger than max_allowed_packet are not allowed..
        /// </summary>
        public static string QueryTooLarge
        {
            get
            {
                return _resourceManager.GetString("QueryTooLarge", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reading from the stream has failed..
        /// </summary>
        public static string ReadFromStreamFailed
        {
            get
            {
                return _resourceManager.GetString("ReadFromStreamFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid attempt to read a prior column using SequentialAccess.
        /// </summary>
        public static string ReadingPriorColumnUsingSeqAccess
        {
            get
            {
                return _resourceManager.GetString("ReadingPriorColumnUsingSeqAccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Replicated connections allow only readonly statements..
        /// </summary>
        public static string ReplicatedConnectionsAllowOnlyReadonlyStatements
        {
            get
            {
                return _resourceManager.GetString("ReplicatedConnectionsAllowOnlyReadonlyStatements", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Routine &apos;{0}&apos; cannot be found. Either check the spelling or make sure you have sufficient rights to execute the routine..
        /// </summary>
        public static string RoutineNotFound
        {
            get
            {
                return _resourceManager.GetString("RoutineNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Attempt to call stored function &apos;{0}&apos; without specifying a return parameter.
        /// </summary>
        public static string RoutineRequiresReturnParameter
        {
            get
            {
                return _resourceManager.GetString("RoutineRequiresReturnParameter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connector/Net no longer supports server versions prior to 5.0.
        /// </summary>
        public static string ServerTooOld
        {
            get
            {
                return _resourceManager.GetString("ServerTooOld", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Snapshot isolation level is not supported..
        /// </summary>
        public static string SnapshotNotSupported
        {
            get
            {
                return _resourceManager.GetString("SnapshotNotSupported", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Socket streams do not support seeking.
        /// </summary>
        public static string SocketNoSeek
        {
            get
            {
                return _resourceManager.GetString("SocketNoSeek", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Retrieving procedure metadata for {0} from procedure cache..
        /// </summary>
        public static string SoftProcQuery
        {
            get
            {
                return _resourceManager.GetString("SoftProcQuery", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stored procedures are not supported on this version of MySQL.
        /// </summary>
        public static string SPNotSupported
        {
            get
            {
                return _resourceManager.GetString("SPNotSupported", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The stream has already been closed.
        /// </summary>
        public static string StreamAlreadyClosed
        {
            get
            {
                return _resourceManager.GetString("StreamAlreadyClosed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to  The stream does not support reading.
        /// </summary>
        public static string StreamNoRead
        {
            get
            {
                return _resourceManager.GetString("StreamNoRead", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The stream does not support writing.
        /// </summary>
        public static string StreamNoWrite
        {
            get
            {
                return _resourceManager.GetString("StreamNoWrite", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding..
        /// </summary>
        public static string Timeout
        {
            get
            {
                return _resourceManager.GetString("Timeout", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to error connecting: Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached..
        /// </summary>
        public static string TimeoutGettingConnection
        {
            get
            {
                return _resourceManager.GetString("TimeoutGettingConnection", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0}: Connection Closed.
        /// </summary>
        public static string TraceCloseConnection
        {
            get
            {
                return _resourceManager.GetString("TraceCloseConnection", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to trace.  There are more than Int32.MaxValue connections in use..
        /// </summary>
        public static string TraceErrorMoreThanMaxValueConnections
        {
            get
            {
                return _resourceManager.GetString("TraceErrorMoreThanMaxValueConnections", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0}: Error encountered during row fetch. Number = {1}, Message={2}.
        /// </summary>
        public static string TraceFetchError
        {
            get
            {
                return _resourceManager.GetString("TraceFetchError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0}: Connection Opened: connection string = &apos;{1}&apos;.
        /// </summary>
        public static string TraceOpenConnection
        {
            get
            {
                return _resourceManager.GetString("TraceOpenConnection", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0}: Error encountered attempting to open result: Number={1}, Message={2}.
        /// </summary>
        public static string TraceOpenResultError
        {
            get
            {
                return _resourceManager.GetString("TraceOpenResultError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0}: Query Closed.
        /// </summary>
        public static string TraceQueryDone
        {
            get
            {
                return _resourceManager.GetString("TraceQueryDone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0}: Query Normalized: {2}.
        /// </summary>
        public static string TraceQueryNormalized
        {
            get
            {
                return _resourceManager.GetString("TraceQueryNormalized", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0}: Query Opened: {2}.
        /// </summary>
        public static string TraceQueryOpened
        {
            get
            {
                return _resourceManager.GetString("TraceQueryOpened", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0}: Resultset Opened: field(s) = {1}, affected rows = {2}, inserted id = {3}.
        /// </summary>
        public static string TraceResult
        {
            get
            {
                return _resourceManager.GetString("TraceResult", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0}: Resultset Closed. Total rows={1}, skipped rows={2}, size (bytes)={3}.
        /// </summary>
        public static string TraceResultClosed
        {
            get
            {
                return _resourceManager.GetString("TraceResultClosed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0}: Set Database: {1}.
        /// </summary>
        public static string TraceSetDatabase
        {
            get
            {
                return _resourceManager.GetString("TraceSetDatabase", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0}: Statement closed: statement id = {1}.
        /// </summary>
        public static string TraceStatementClosed
        {
            get
            {
                return _resourceManager.GetString("TraceStatementClosed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0}: Statement executed: statement id = {1}.
        /// </summary>
        public static string TraceStatementExecuted
        {
            get
            {
                return _resourceManager.GetString("TraceStatementExecuted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0}: Statement prepared: sql=&apos;{1}&apos;, statement id={2}.
        /// </summary>
        public static string TraceStatementPrepared
        {
            get
            {
                return _resourceManager.GetString("TraceStatementPrepared", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0}: Usage Advisor Warning: Query is using a bad index.
        /// </summary>
        public static string TraceUAWarningBadIndex
        {
            get
            {
                return _resourceManager.GetString("TraceUAWarningBadIndex", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0}: Usage Advisor Warning: The field &apos;{2}&apos; was converted to the following types: {3}.
        /// </summary>
        public static string TraceUAWarningFieldConversion
        {
            get
            {
                return _resourceManager.GetString("TraceUAWarningFieldConversion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0}: Usage Advisor Warning: Query does not use an index.
        /// </summary>
        public static string TraceUAWarningNoIndex
        {
            get
            {
                return _resourceManager.GetString("TraceUAWarningNoIndex", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0}: Usage Advisor Warning: The following columns were not accessed: {2}.
        /// </summary>
        public static string TraceUAWarningSkippedColumns
        {
            get
            {
                return _resourceManager.GetString("TraceUAWarningSkippedColumns", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0}: Usage Advisor Warning: Skipped {2} rows. Consider a more focused query..
        /// </summary>
        public static string TraceUAWarningSkippedRows
        {
            get
            {
                return _resourceManager.GetString("TraceUAWarningSkippedRows", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0}: MySql Warning: Level={1}, Code={2}, Message={3}.
        /// </summary>
        public static string TraceWarning
        {
            get
            {
                return _resourceManager.GetString("TraceWarning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to any of the specified MySQL hosts..
        /// </summary>
        public static string UnableToConnectToHost
        {
            get
            {
                return _resourceManager.GetString("UnableToConnectToHost", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to derive stored routine parameters.  The &apos;Parameters&apos; information schema table is not available and access to the stored procedure body has been disabled..
        /// </summary>
        public static string UnableToDeriveParameters
        {
            get
            {
                return _resourceManager.GetString("UnableToDeriveParameters", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to enable query analysis.  Be sure the MariaDB.Data.EMTrace assembly is properly located and registered..
        /// </summary>
        public static string UnableToEnableQueryAnalysis
        {
            get
            {
                return _resourceManager.GetString("UnableToEnableQueryAnalysis", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An error occured attempting to enumerate the user-defined functions.  Do you have SELECT privileges on the mysql.func table?.
        /// </summary>
        public static string UnableToEnumerateUDF
        {
            get
            {
                return _resourceManager.GetString("UnableToEnumerateUDF", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to execute stored procedure &apos;{0}&apos;..
        /// </summary>
        public static string UnableToExecuteSP
        {
            get
            {
                return _resourceManager.GetString("UnableToExecuteSP", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to There was an error parsing the foreign key definition..
        /// </summary>
        public static string UnableToParseFK
        {
            get
            {
                return _resourceManager.GetString("UnableToParseFK", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve stored procedure metadata for routine &apos;{0}&apos;.  Either grant  SELECT privilege to mysql.proc for this user or use &quot;check parameters=false&quot; with  your connection string..
        /// </summary>
        public static string UnableToRetrieveParameters
        {
            get
            {
                return _resourceManager.GetString("UnableToRetrieveParameters", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to start a second async operation while one is running..
        /// </summary>
        public static string UnableToStartSecondAsyncOp
        {
            get
            {
                return _resourceManager.GetString("UnableToStartSecondAsyncOp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unix sockets are not supported on Windows.
        /// </summary>
        public static string UnixSocketsNotSupported
        {
            get
            {
                return _resourceManager.GetString("UnixSocketsNotSupported", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The requested column value could not be treated as or conveted to a Guid..
        /// </summary>
        public static string ValueNotSupportedForGuid
        {
            get
            {
                return _resourceManager.GetString("ValueNotSupportedForGuid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Writing to the stream failed..
        /// </summary>
        public static string WriteToStreamFailed
        {
            get
            {
                return _resourceManager.GetString("WriteToStreamFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; is not found but a parameter with the name &apos;{1}&apos; is found. Parameter names must include the leading parameter marker..
        /// </summary>
        public static string WrongParameterName
        {
            get
            {
                return _resourceManager.GetString("WrongParameterName", resourceCulture);
            }
        }

    }
}